/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rdaCS5BUcld
 */
import { CardContent, CardHeader, Card } from "@/components/ui/card";

export function VOCard() {
  return (
    <section className="w-full pt-6 md:pt-12">
      <div className="container px-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <Card className="flipped" onClick={undefined}>
            <CardContent className="flex items-center">
              <img
                alt="Image"
                className="aspect-square object-cover rounded-lg"
                height="200"
                src="/img/tessaract.jpg"
                width="100%"
              />
            </CardContent>
            <CardHeader className="flex flex-col min-h-[200px]">
              <h2 className="text-2xl font-bold">
                Getting started with Shadcn components
              </h2>
              <p className="flex-1 my-4 text-sm text-gray-500 dark:text-gray-400">
                Shadcn components are designed to be practical, accessible, and
                highly customizable. This guide will walk you through the
                process of integrating Shadcn components into your web projects.
              </p>
            </CardHeader>
            <CardContent className="flex items-center">
              <div className="flex-1 my-4 text-sm text-gray-500 dark:text-gray-400">
                More information about Shadcn components...
              </div>
            </CardContent>
          </Card>
          <Card className="flipped" onClick={undefined}>
            <CardContent className="flex items-center">
              <img
                alt="Image"
                className="aspect-square object-cover rounded-lg"
                height="200"
                src="/placeholder.svg"
                width="100%"
              />
            </CardContent>
            <CardHeader className="flex flex-col min-h-[200px]">
              <h2 className="text-2xl font-bold">
                Getting started with Shadcn components
              </h2>
              <p className="flex-1 my-4 text-sm text-gray-500 dark:text-gray-400">
                Shadcn components are designed to be practical, accessible, and
                highly customizable. This guide will walk you through the
                process of integrating Shadcn components into your web projects.
              </p>
            </CardHeader>
            <CardContent className="flex items-center">
              <div className="flex-1 my-4 text-sm text-gray-500 dark:text-gray-400">
                More information about Shadcn components...
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  );
}
